raulwwq0/pinia-spanish-docs

cookbook/index.md, cookbook/migration-vuex.md
In this small advance, work has been done on the home page of the cookbook as well as on the vuex migration page.
=> docs: translation in cookbook section

core-concepts/actions.md, core-concepts/getters.md
Added translation to `getters.md` and `actions.md`.
=> docs(core-concepts): getters.md and actions.md translated

cookbook/index.md, cookbook/testing.md
1. Add the correct translation for "testing store" in the main index about cookbook
2. Update English anchors (index or menu) in testing page
=> fix(cookbook): Update english anchors

cookbook/composables.md
1. Add translation to composables.md
=> docs(cookbook): Add translation to composables.md

cookbook/migration-0-0-7.md
Add translation to **migration-0-0-7.md** file
=> docs(cookbook): Add translation to migration-0-0-7.md

.vitepress/locales/es.js, api/enums/pinia.MutationType.md, api/index.md, api/interfaces/pinia.DefineSetupStoreOptions.md, api/interfaces/pinia.DefineStoreOptions.md, api/interfaces/pinia.DefineStoreOptionsBase.md, api/interfaces/pinia.DefineStoreOptionsInPlugin.md, api/interfaces/pinia.MapStoresCustomization.md, api/interfaces/pinia.Pinia.md, api/interfaces/pinia.PiniaCustomProperties.md, api/interfaces/pinia.PiniaCustomStateProperties.md, api/interfaces/pinia.PiniaPlugin.md, api/interfaces/pinia.PiniaPluginContext.md, api/interfaces/pinia.StoreDefinition.md, api/interfaces/pinia.StoreProperties.md, api/interfaces/pinia.SubscriptionCallbackMutationDirect.md, api/interfaces/pinia.SubscriptionCallbackMutationPatchFunction.md, api/interfaces/pinia.SubscriptionCallbackMutationPatchObject.md, api/interfaces/pinia._StoreOnActionListenerContext.md, api/interfaces/pinia._StoreWithState.md, api/interfaces/pinia._SubscriptionCallbackMutationBase.md, api/interfaces/pinia_testing.TestingOptions.md, api/interfaces/pinia_testing.TestingPinia.md, api/modules/pinia.md, api/modules/pinia_nuxt.md, api/modules/pinia_testing.md, cookbook/testing.md
Add **api** folder from original docs to translate and also fix some links to use these new files.
=> feat: add api files to translate

core-concepts/outside-component-usage.md, core-concepts/plugins.md
Added translation to _plugins.md_ and  _outside-component-usage.md_.
=> docs: plugins.md and outside-component-usage.md translated

.vitepress/locales/es.js, cookbook/composables.md, core-concepts/index.md, introduction.md, ssr/index.md, ssr/nuxt.md
Both files from _ssr section_ translated and some translation fixes
=> docs(ssr): index.md and nuxt.md translated

.vitepress/locales/es.js, api/enums/pinia.MutationType.md, api/index.md
- Update locale
- Apply translation to: 
```
api/index.md
api/enums/pinia.MutationType.md
```
=> chore: Add translation to enums

.vitepress/components/sponsors.json, .vitepress/theme/Layout.ts
resolves #16
Cherry picked from https://github.com/vuejs/pinia/commit/f5897d0673419164410311d658f45d0201262ff0
=> docs: update sponsors (#16)

api/interfaces/pinia_testing.TestingOptions.md, api/interfaces/pinia_testing.TestingPinia.md
_Translate the files:_
- `pinia_testing.TestingOptions.md`
- `pinia_testing.TestingPinia.md`
Will close issue #19
=> docs: Translate the `[api/interfaces]` section

api/modules/pinia.md, api/modules/pinia_nuxt.md, api/modules/pinia_testing.md
Translate all files from the _modules_ folder.
=> docs(api): modules section translated

api/interfaces/pinia.DefineSetupStoreOptions.md, api/interfaces/pinia.DefineStoreOptions.md, api/interfaces/pinia.DefineStoreOptionsBase.md
_Translate the files_
- `pinia.DefineStoreOptions.md`
- `pinia.DefineStoreOptionsBase.md`
- `pinia.DefineSetupStoreOptions.md`
=> add: translated files with anchor headers

api/interfaces/pinia.DefineStoreOptionsInPlugin.md, api/interfaces/pinia.MapStoresCustomization.md, api/interfaces/pinia.Pinia.md, api/interfaces/pinia.PiniaCustomProperties.md
_Translate the following files:_
- `pinia.DefineStoreOptionsInPlugin.md`
- `pinia.MapStoresCustomization.md`
- `pinia.Pinia.md`
- `pinia.PiniaCustomProperties`
=> translate: [api/interfaces/] 4 following files

api/interfaces/pinia.PiniaCustomStateProperties.md, api/interfaces/pinia.PiniaPlugin.md, api/interfaces/pinia.PiniaPluginContext.md, api/interfaces/pinia.StoreDefinition.md, api/interfaces/pinia.StoreProperties.md
_Translate the following files:_
- `pinia.PiniaCustomStateProperties.md`
- `pinia.PiniaPlugin.md`
- `pinia.PiniaPluginContext.md`
- `pinia.StoreDefinition.md`
- `pinia.StoreProperties.md`
=> translate: `[api/interfaces]` 5 more files

.gitignore, core-concepts/actions.md
Remove comma from import in **actions.md**. This wil close #32
=> docs: syntax error of import statement

api/interfaces/pinia._StoreWithState.md
Translate missing comments in some examples.
=> fix(api/interfaces): missed translation in examples

.vitepress/config/shared.ts
Working search bar using Algolia DocSearch
=> feat: algolia search

cookbook/composables.md, cookbook/composing-stores.md
- [] Feature :sparkles:
Solve #54 and #59
=> docs: solve #54 and #59

.vitepress/config/shared.ts, core-concepts/getters.md, core-concepts/plugins.md
=> docs: sync docs with the official ones

api/interfaces/pinia_testing.TestingOptions.md, api/modules/pinia.md, cookbook/composing-stores.md, core-concepts/actions.md, core-concepts/outside-component-usage.md, package-lock.json, package.json
Sync docs with the official ones. Resolve #75 #78 #79 #80 #81
=> docs: sync

.vitepress/config/es.ts, .vitepress/config/index.ts, .vitepress/theme/styles/vars.css, api/interfaces/pinia.PiniaCustomProperties.md, api/interfaces/pinia.PiniaPlugin.md, api/interfaces/pinia.StoreDefinition.md, api/interfaces/pinia._StoreWithState.md, api/interfaces/pinia_testing.TestingOptions.md, api/modules/pinia.md, api/modules/pinia_nuxt.md, cookbook/testing.md, cookbook/vscode-snippets.md, core-concepts/index.md, core-concepts/state.md, package-lock.json, package.json, ssr/index.md, ssr/nuxt.md
Implement changes from current open issues
=> docs: Sync changes

.vitepress/theme/components/VueSchoolLink.vue
resolves #114
Cherry picked from https://github.com/vuejs/pinia/commit/cbbe62db8f9d3de859ecb7e8eec2cd52259629f4
=> docs: broken play button on Vue School links (#114)
